repos:
  # default hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # black
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  # local
  - repo: local
    hooks:
      # wemake-python-styleguide
      - id: flake8
        name: wemake-python-styleguide
        entry: flake8
        language: python
        types: [ python ]
      # tests
      - id: tests
        name: tests
        entry: pytest
        language: system
        types: [ python ]
        stages: [ pre-push ]
      # coverage
      - id: coverage
        name: coverage
        entry: make coverage
        language: system
        types: [ python ]
        stages: [ pre-push ]
